### ISSUE TITLE
Dashboard link broken on some binder deployments.

### ISSUE THREAD

**Issue by willirath** [dask/dask-examples#128]
See <https://discourse.jupyter.org/t/gesis-hub-blocks-dask-dashboard/3019>.

With
<https://github.com/dask/dask-examples/blob/c14b7dc809c17066224cb5b8353e78c9aebe9ccc/binder/start#L4> 
assuming that the full URL always is along the lines of `https://binder.something.example.com/user/${JUPYTERHUB_USER}/proxy/8787` which is not necessarily true.

**Comment by quasiben** [comment]
@TomAugspurger i don't have write access to this repo .  Can you take a look and/or give me commit writes ?

**Comment by TomAugspurger** [comment]
@quasiben added.
