### ISSUE TITLE
Binder notebook "training-on-large-datasets.ipynb" fails when importing dask_ml.cluster

### ISSUE THREAD

**Issue by tslott** [dask/dask-examples#133]
The notebook imports on old version of dask-ml. Fix this by updating binder/environment.yml to use newer version of dask-ml.

dask-ml=1.1.1 -> dask-ml=1.2.0

**Comment by TomAugspurger** [comment]
What's the actual traceback?

**Comment by tslott** [comment]
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-001abd10b0d1> in <module>
      1 import dask_ml.datasets
----> 2 import dask_ml.cluster
      3 import matplotlib.pyplot as plt

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_ml/cluster/__init__.py in <module>
      1 """Unsupervised Clustering Algorithms"""
      2 
----> 3 from .k_means import KMeans  # noqa
      4 from .minibatch import PartialMiniBatchKMeans  # noqa
      5 from .spectral import SpectralClustering  # noqa

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_ml/cluster/k_means.py in <module>
     21 )
     22 from ..utils import _timed, _timer, check_array, row_norms
---> 23 from ._compat import _k_init
     24 
     25 logger = logging.getLogger(__name__)

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_ml/cluster/_compat.py in <module>
      2 
      3 if SK_022:
----> 4     from sklearn.cluster._k_means import _k_init
      5 else:
      6     from sklearn.cluster.k_means_ import _k_init

ModuleNotFoundError: No module named 'sklearn.cluster._k_means'`

Looks like the following is from the old version, which is updated in 1.2.0.
`3 if SK_022:
----> 4     from sklearn.cluster._k_means import _k_init
      5 else:
      6     from sklearn.cluster.k_means_ import _k_init`

**Comment by tslott** [comment]
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-001abd10b0d1> in <module>
      1 import dask_ml.datasets
----> 2 import dask_ml.cluster
      3 import matplotlib.pyplot as plt

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_ml/cluster/__init__.py in <module>
      1 """Unsupervised Clustering Algorithms"""
      2 
----> 3 from .k_means import KMeans  # noqa
      4 from .minibatch import PartialMiniBatchKMeans  # noqa
      5 from .spectral import SpectralClustering  # noqa

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_ml/cluster/k_means.py in <module>
     21 )
     22 from ..utils import _timed, _timer, check_array, row_norms
---> 23 from ._compat import _k_init
     24 
     25 logger = logging.getLogger(__name__)

/srv/conda/envs/notebook/lib/python3.7/site-packages/dask_ml/cluster/_compat.py in <module>
      2 
      3 if SK_022:
----> 4     from sklearn.cluster._k_means import _k_init
      5 else:
      6     from sklearn.cluster.k_means_ import _k_init

ModuleNotFoundError: No module named 'sklearn.cluster._k_means'

Looks like the following is from an old version. It is updated in 1.2.0

```
      3 if SK_022:
----> 4     from sklearn.cluster._k_means import _k_init
      5 else:
      6     from sklearn.cluster.k_means_ import _k_init
```

**Comment by TomAugspurger** [comment]
Thanks.

**Comment by martindurant** [comment]
@TomAugspurger , was this resolved?

**Comment by TomAugspurger** [comment]
Yep, resolved in dask-ml.
