### ISSUE TITLE
`predictions = dask.compute(*predictions)` gives errror for torch-prediction.ipynb file

### ISSUE THREAD

**Issue by fatsoengineer** [dask/dask-examples#138]
I was running the notebook for batch prediction 
The following code gave an error : `predictions = dask.compute(*predictions)`
Error:
`TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not builtin_function_or_method`

I can't figure out why. Any solutions?

**Comment by TomAugspurger** [comment]
Can you post the full traceback?

**Comment by fatsoengineer** [comment]
> Can you post the full traceback?

TypeError                                 Traceback (most recent call last)
<ipython-input-26-1daab7e2a510> in <module>
----> 1 predictions = dask.compute(*predictions)
      2 predictions

/mydata/anaconda3/envs/detectron_2/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

/mydata/anaconda3/envs/detectron_2/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2593                     should_rejoin = False
   2594             try:
-> 2595                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2596             finally:
   2597                 for f in futures.values():

/mydata/anaconda3/envs/detectron_2/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1891                 direct=direct,
   1892                 local_worker=local_worker,
-> 1893                 asynchronous=asynchronous,
   1894             )
   1895 

/mydata/anaconda3/envs/detectron_2/lib/python3.6/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    778         else:
    779             return sync(
--> 780                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    781             )
    782 

/mydata/anaconda3/envs/detectron_2/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    346     if error[0]:
    347         typ, exc, tb = error[0]
--> 348         raise exc.with_traceback(tb)
    349     else:
    350         return result[0]

/mydata/anaconda3/envs/detectron_2/lib/python3.6/site-packages/distributed/utils.py in f()
    330             if callback_timeout is not None:
    331                 future = asyncio.wait_for(future, callback_timeout)
--> 332             result[0] = yield future
    333         except Exception as exc:
    334             error[0] = sys.exc_info()

/mydata/anaconda3/envs/detectron_2/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/mydata/anaconda3/envs/detectron_2/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1750                             exc = CancelledError(key)
   1751                         else:
-> 1752                             raise exception.with_traceback(traceback)
   1753                         raise exc
   1754                     if errors == "skip":

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not builtin_function_or_method

**Comment by TomAugspurger** [comment]
Thanks. It'll be a while before I can take another look. Are you able to
run through things and see what's going wrong?

**Comment by martindurant** [comment]
@fatsoengineer , any further details?
@TomAugspurger , anyone else who might help here?

**Comment by TomAugspurger** [comment]
Not sure.

**Comment by anaszain89** [comment]
@TomAugspurger / @martindurant 
I was working with this notebook too.. This error stems from an issue in the line 
```
batches = [dask.delayed(torch.stack)(torch.stack)
           for batch in toolz.partition_all(10, tensors)]
```
This should be 
```
batches = [dask.delayed(torch.stack)(batch)
           for batch in toolz.partition_all(10, tensors)]
```
That still runs into an issue `KilledWorker: ('load-87d45322-2b06-4144-ae54-d4b8035961bd', )`. This is because the model is on the GPU at the end of fine-tuning. Moving it back to the CPU `dmodel = dask.delayed(model.cpu())` removes this error and prediction runs fine. 

I was also looking at extending the example and running inference on GPUs. I can extend the notebook to add GPU based inference and submit a PR if that is of interest.

**Comment by martindurant** [comment]
Ooops, indeed that looks like it should have been `(batch)`. Definitely please put that in a PR. If indeed it needs to move gpu->cpu, that had better come with a comment in the text.

To extend should maybe come as a separate PR, but I'm sure we'd be happy to see it.
