### ISSUE TITLE
doc: link dataframe-groupby aggregate to 02-groupby

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-examples#150]
Would be good to have a link to https://docs.dask.org/en/latest/dataframe-groupby.html#aggregate in https://github.com/dask/dask-examples/blob/master/dataframes/02-groupby.ipynb

This is probably more so because googling dask dataframe group by takes me to https://examples.dask.org/dataframes/02-groupby.html and I know there is more info in the docs https://docs.dask.org/en/latest/dataframe-groupby.html#aggregate

**Comment by TomAugspurger** [comment]
Agreed. A short section saying that dd.Aggregation is available for custom
aggregations would be welcome.
