### ISSUE TITLE
Machine Learning broken link

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask-examples#155]
At the bottom of

https://examples.dask.org/machine-learning.html#Training-on-Large-Datasets

For all the estimators implemented in Dask-ML, see the API documentation.

Points to https://dask-ml.readthedocs.io/en/latest/modules/.html

Should be https://ml.dask.org/modules/api.html# ?

**Comment by TomAugspurger** [comment]
Yep, https://ml.dask.org/modules/api.html# is the right target.
