### ISSUE TITLE
Include outputs in notebooks

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#16]
In https://github.com/dask/dask-examples/pull/14#issuecomment-401507027 @stsievert says 

> I see most of the other notebooks in this repo are without their outputs in the notebook. Letting the outbooks be coded in the notebook would lower the barrier to viewing to viewing these notebooks by allowing users to try binder if they want. Why don't we include the outputs in the notebooks?

This seemed to be worth discussion, so I've raised a separate issue for it here.

**Comment by mrocklin** [comment]
When working in project repositories like dask/dask or dask/dask-ml we always strip outputs of example notebooks to keep the size of the repository small.  Otherwise every time someone re-runs the notebook and produces an output plot the repo grows by a several hundred kB.  Aggregated over years of time the repository bloats out.

However, hygiene around this repository isn't as strict as with those.  Modest outputs might be ok?  What do others think?

**Comment by martindurant** [comment]
I agree that "examples" have a decent argument for being rendered, where as "tutorials" should not be, since they are intended to be downloaded and run by users.

**Comment by mrocklin** [comment]
I'm going to close this.  Our solution was to run the notebooks and then place their evaluated forms on https://example.dask.org

**Comment by stsievert** [comment]
> then place their evaluated forms on https://examples.dask.org

:+1: that’s an even better solution!
