### ISSUE TITLE
Add example for dealing with satellite imagery

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#20]
[This notebook](https://gist.github.com/mrocklin/3df315e93d4bdeccf76db93caca2a9bd) demonstrates using XArray and Dask with a large satellite image.  It downloads the image from S3 with rasterio and then loads it in chunks.  

It doesn't do a whole lot with it afterwards though, which presumably we should change.  This, along with ensuring that the computation we choose also fits nicely in RAM (might have to play around with chunk sizes a bit) is presumably the hard part of this exercise.

Additionally, there is an open question of whether or not we should include rasterio in the docker image (I suspect that it brings in GDAL, which would greatly increase the image size).  Instead we might include a `!pip install xarray rasterio` line or something similar at the top of the notebook.

**Comment by guillaumeeb** [comment]
I'm interested in this example, maybe I can work on it if I have find some time, this is typically something which can be of interest at CNES.

I can propose a basic example on satellite imagery which is NDVI computation, it just need an image with NIR band, which can be found in Sentinel 2 images.

See https://developers.google.com/earth-engine/tutorial_api_06 for an example.

We could compute that and display it in a plot.

**Comment by mrocklin** [comment]
That would be quite welcome

**Comment by guillaumeeb** [comment]
I think this issue is closed by #60!

**Comment by mrocklin** [comment]
Indeed.  Thanks @rmsare !
