### ISSUE TITLE
Find good XArray example

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#21]
The [XArray docs](http://xarray.pydata.org/en/stable/) likely have some good informative examples that we could include in this repository.  We might also consider including XArray in the environment.

cc @shoyer @jhamman for insight

XArray might also want to fork and make their own repository, but they'd be welcome here as well

**Comment by mrocklin** [comment]
I thought I'd ping on this.  It would be great to include an Xarray example on dask.examples.org (a combination static HTML site and runnable binder).  Xarray folks, any interest?  This site gets decent traffic and would be, I think, good advertising for Xarray

**Comment by jhamman** [comment]
Are you thinking something beyond what I did in #51: https://examples.dask.org/xarray.html?

**Comment by mrocklin** [comment]
Ah, nope.  That's great.  Just an oversight on my part. Closing!
