### ISSUE TITLE
Automatically clear notebook output

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-examples#220]
Over in https://github.com/dask/dask-examples/pull/218 @bryanwweber mentioned he used `jupyter nbconvert --clear-output --inplace` to automatically clear the output from the example notebooks (xref https://github.com/dask/dask-examples/pull/218#discussion_r864965302). It would be great if there was some way we could automatically have this happen, for example in a `pre-commit` hook or something, to avoid accidentally committing notebooks that have output already

**Comment by jsignell** [comment]
Looks like we can use [nbstripout](https://github.com/kynan/nbstripout/) like:

```python
repos:
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.0
  hooks:
    - id: nbstripout
 ```
