### ISSUE TITLE
Website missing `dask-sphinx-theme` font

### ISSUE THREAD

**Issue by charlesbluca** [dask/dask-examples#224]
After the bump to the new `dask-sphinx-theme`, it looks like the examples page isn't picking up the font being used on all other Dask pages for some reason:

![image](https://user-images.githubusercontent.com/20627856/173467451-350711c5-40bf-4e8a-aca4-f9b74d709254.png)

In contrast to Dask's documentation:

![image](https://user-images.githubusercontent.com/20627856/173468104-b93a3b59-4082-41bb-bae5-d9e49e3396b3.png)

Do these fonts need to be added manually to the `gh-pages` branch?

**Comment by jacobtomlinson** [comment]
Thanks @charlesbluca! I've opened https://github.com/dask/dask-sphinx-theme/pull/77 to switch back from vendored fonts to CDN hosted ones which should resolve this issue.

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask-sphinx-theme/pull/77. Thanks @charlesbluca for reporting and @jacobtomlinson for fixing
