### ISSUE TITLE
Large scale XGBoost example with HyperParameter Optimization

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#230]
*I'm abusing this issue tracker a bit, but it seemed better than bringing this to, say, dask/community*

I'd like us to think about doing a larger workflow study around XGBoost and some related technologies (xgboost.dask, optuna, maybe snowflake).  I've seen a few groups in the wild try to combine these technologies with varied success.  This would also, I think, have some impact.  

Broadly, people have a large volume of data, and want to train XGBoost on that data, performing some hyperparameter optimization along the way.  There are at least a couple different configurations:

1.  Train lots of small XGBoost problems, parallelizing on HPO using something like Optuna (https://github.com/optuna/optuna/pull/2023 is promising)
2. Train with xgboost.dask using an entire Dask cluster, still doing HPO, but now sequentially (my guess is that xgboost.dask will take over the entire cluster, and this isn't great)
3. Train with xgboost.dask, using many entire Dask clusters, doing HPO but leveraging some job manager (kubernetes, coiled) to run a new Dask cluster in each job.

```python
def objective(trial):
    with coiled.Cluster(...) as cluster:
        with dask.distributed.Client(cluster) as client:
            train ...
```

Some things to play with ...

1.  Storage: Parquet vs Snowflake
2. Compute: x86 vs ARM vs GPU

Speaking for folks at Coiled I think that we'd be good at ...

1.  Getting Dask and Optuna working well together (@jrbourbeau )
2. Figuring out cloud accounts to run things (this is trivial for us)
3. Actually running lots of experiments quantitatively and looking at results (@hayesgb and team have gotten good at this)

We could use help on  ...

1. Figuring out a good dataset to train on
2. Defining the objective function and parameter space
3. Interpretting success of the training
4. Making sure that we're doing GPU magic ✨ correctly 

@mmccarty has a notebook here that his team was playing with https://github.com/rapidsai/cloud-ml-examples/blob/main/gke-dask/notebooks/xgboost-gpu-hpo-job-parallel-k8s.ipynb

**Comment by mrocklin** [comment]
@mmccarty I played with your notebook here: https://gist.github.com/mrocklin/19c41a28739c4205498b4fc6bc6a21fc

I made a few small changes:

1. I use the new Dask+Optuna work.  Mostly this means that you don't need to set up a MySQL database.
2. I use Coiled rather than Kubernetes, both for convenience, and so that I could get the Optuna work to the cluster easily
3. I didn't use GPUs, mostly because I'm lazy (but this could be reversed pretty easily I hope)

cc also @rrpelgrim

**Comment by mrocklin** [comment]
More nicely rendered with Yuvi's thing: https://notebooksharing.space/view/d73b8a569123452dc41f3686013ee814b59a24161af8d7f62ace1f9e26ae56fd#displayOptions=

**Comment by mmccarty** [comment]
Thanks for the feedback, @mrocklin !

> I use the new Dask+Optuna work. Mostly this means that you don't need to set up a MySQL database.

Yeah, the MySQL db was just a temporary work-around. Looking forward to that optuna PR landing.

[This dataset](https://www.kaggle.com/competitions/amex-default-prediction/data?select=train_data.csv) looks interesting and  fun for GPUs.

**Comment by mrocklin** [comment]
@mmccarty if you or folks around you has recommendations for what a dataset + problem at a more interesting size would be I'd be curious about that.  My experience with the notebook above was that training times were very fast (even on CPU).  I see the dataset that you've pointed to above.  Any chance you all have taken a crack at it yet?

Also, any ideas on larger datasets appropriate for multi-node?

**Comment by jacobtomlinson** [comment]
cc @hcho3

**Comment by mmccarty** [comment]
Not yet that I'm aware of, but I believe Philip is looking at adding that dataset. Would love to see a multi-node example!

**Comment by mrocklin** [comment]
Example structure of what I would recommend as a first pass for a dask-xgboost approach (lots of dask clusters)

https://gist.github.com/mrocklin/4073ade8e1a32c52525fe897e4014943

**Comment by mrocklin** [comment]
Or, perhaps simpler if the time to train is much longer than the time to start a Dask cluster: https://gist.github.com/mrocklin/41b09457f1976f8af22ce72a9133586a

**Comment by mrocklin** [comment]
Here is a concrete example of the xgboost.dask + optuna + threads approach: https://gist.github.com/mrocklin/c5e4d222327a2aa1ca3ffdf891f04ffe

Example courtesy of of @dankerrigan 

This required a few upstream fixes

**Comment by mrocklin** [comment]
A small video showing it working, and some recent changes: https://www.loom.com/share/80daac5c01a74dcc9f879baf17e4c1b2

**Comment by mrocklin** [comment]
@fjetter just reporting that I can run the notebook above with code that is currently on `main`.  Thank you for pushing things through.  It would be slightly nicer if `with client.as_current()` was default under `with client`, but my primary needs are met.

**Comment by trivialfis** [comment]
Hi, exciting work! Just want to clarify a little bit. XGBoost uses the workers that contain the data, which may or may not be the entire cluster. I think it's possible if the caller wants to control the workers that xgboost use by assigning data partitions, but I'm not sure if that's more efficient than letting XGBoost take the entire cluster and just launch many clusters.

**Comment by mrocklin** [comment]
Good to know!  In this case I think it's probably simpler just to stand up
many Dask clusters (assuming you have an easy way to do that).

**Comment by hayesgb** [comment]
For those that are interested, this work is described [here](https://blog.coiled.io/blog/xgboost-at-scale/) and [here](https://github.com/coiled/dask-xgboost-nyctaxi)

**Comment by crusaderky** [comment]
Could this be closed by https://github.com/coiled/dask-xgboost-nyctaxi?
Notably those notebooks don't cover
> Train lots of small XGBoost problems, parallelizing on HPO using something like Optuna 
but that could be addressed easily with an extra nb in the same project.

**Comment by jacobtomlinson** [comment]
I would only say that repo closes this issue if the plan is to upstream those notebooks here.

**Comment by ncclementi** [comment]
@jacobtomlinson how would we upstream the notebooks, given that the resources needed to run such big data will imply using clusters, we used coiled ones. But I'm not sure how folks feel about using the coiled clusters on this repo. Plus it would be good to have examples that folks can run without needing a beefy cluster. 

Unless you had anything else in mind and I'm not following. 

I'm happy to collaborate on this, especially after seeing that even the simple XGBoost example is completely out of date.

**Comment by jacobtomlinson** [comment]
Yeah given that this is an OSS repo it would be best for the notebooks to use OSS clusters. 

It would also be good for the examples here to work on your local machine. But if some smaller XGBoost examples were added here I think folks would be fine linking from them to the Coiled examples as further reading.

I guess my point is that I don't think the existence of that repo closes this issue on its own.

**Comment by jacobtomlinson** [comment]
_Side note: if anyone at Coiled wants to contribute GPU XGBoost examples to the [RAPIDS example notebooks](https://docs.rapids.ai/deployment/stable/examples/index.html), Coiled clusters and all, they would be most welcome._

**Comment by mrocklin** [comment]
My needs for this issue are done.  As I mentioned in my original post I was abusing this issue tracker a bit.  I'm totally in favor of folks adding more examples here, perhaps a more modern xgboost.dask example or an Optuna example?  The full scale optuna + xgboost.dask + multiple clusters thing though doesn't make sense here.  

I'm going to close this issue, pointing to https://github.com/coiled/dask-xgboost-nyctaxi as the result.   We're working now to open up something for larger scale workloads that hopefully comes out in the next couple of months.  If folks want to follow up with issues on this repository around xgboost or optuna I welcome that effort.

@jacobtomlinson nice side note.  I'm curious, can you share more information about how much traffic the RAPIDS notebooks get?  That would be helpful in prioritizing effort on the Coiled side.  

Closing the issue (my original needs are met) but happy to keep conversing here.
