### ISSUE TITLE
Dask slides hyperlink led to "Page not found" error

### ISSUE THREAD

**Issue by ikding** [dask/dask-examples#237]
Not sure if this is the right repo to report, but I'd like to give you a heads-up about an outdated link on dask.org website.

When I click the the "Dask Slides" section on the "presentation" page: https://docs.dask.org/en/latest/presentations.html#dask-slides

I am rerouted to https://www.dask.org/slides, and the screen is showing a getting a "Page not found" error.

![Screenshot 2023-09-19 at 4 14 08 PM](https://github.com/dask/dask-examples/assets/7269845/e5ca04bf-24fb-441c-a50a-1e0c4c0e24af)

**Comment by jacobtomlinson** [comment]
@jrbourbeau no idea I'm afraid.

**Comment by ikding** [comment]
The dask presentation page (https://docs.dask.org/en/latest/presentations.html) no longer has a "Dask Slides" section, so this issue is out of date.
