### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#3]
Thinking optimistically, if we get many examples in this repository, how should we organize them?  I recommend that we have a small number of notebooks at the top level, showing an introduction for each topic like arrays, dataframes, delayed, ML,  ..., and also a directory for topics that have many additional notebooks.

**Comment by mholtzscher** [comment]
I think that would be a very good start. Are you thinking about migrating notebooks from dask-tutorial or old-dask-example? It might be confusing to a new user to see 3 repos with examples and tutorials(It definitely confused me)

**Comment by mrocklin** [comment]
I'm not sure, what do you think would be best?

If we did move things from other other repositories we would want to update and clean them up for the expected runtime environment of this repository: https://github.com/dask/dask-examples#contributing

**Comment by mholtzscher** [comment]
Well I think I would go notebook by notebook and migrate over any content that is relevant/useful. Then add DEPRECATED to repo description and at the top of the README. Optionally then if you want then we could remove notebooks from that repo as they are migrated.

**Comment by mrocklin** [comment]
That sounds great to me :)

**Comment by mholtzscher** [comment]
I will get started on this over the weekend then. Once the CI code is merged it should make checking them easy :)

**Comment by mholtzscher** [comment]
@mrocklin from my initial read through and comparison it looks like this repo has most of the same content. The only difference is the sample projects that looked at nyc taxi data or github. I would say we should start over on example products. Thoughts?

**Comment by mrocklin** [comment]
>  I would say we should start over on example products

I'm not sure what you mean by this exactly.  Can you clarify?

**Comment by kvn219** [comment]
@mrocklin and @mholtzscher  what are some of your thoughts on the way [HoloViews](https://github.com/ioam/holoviews) organized their examples? They have notebooks inside a examples directory with subdirectories. 

<img width="1102" alt="screen shot 2018-04-13 at 9 52 21 am" src="https://user-images.githubusercontent.com/11036038/38738818-1c5c3e9c-3f01-11e8-85cb-0d4c9a836497.png">

In addition, how do we feel about using evaluated notebooks with tools like [nbsphinx](https://nbsphinx.readthedocs.io/en/0.3.2/)?

**Comment by mholtzscher** [comment]
@mrocklin  I meant to say "projects" not "products." :) 

@kvn219 I think that is very close to the goal we have discussed so far. I think There will be some notebooks at high level that are the basics and then folders of more advanced notebooks

**Comment by mrocklin** [comment]
> In addition, how do we feel about using evaluated notebooks with tools like nbsphinx?

@kvn219 I can see how that would be valuable.  Is there an easy way to roll this into the core dask documentation?

**Comment by mrocklin** [comment]
> I recommend that we have a small number of notebooks at the top level, showing an introduction for each topic like arrays, dataframes, delayed, ML, ..., and also a directory for topics that have many additional notebooks.

@stsievert, you're now actually buidling more notebooks for machine learning.  Thoughts on this organization?

**Comment by stsievert** [comment]
>  showing an introduction for each topic ... and also a directory for topics that have many additional notebooks. ... Thoughts on this organization?

That's the organization I've wanted. I've almost done it, but have instead been prefixing with `machine-learning-` when I've wanted a directory `machine-learning/`.

**Comment by stsievert** [comment]
Though right now it is clear visual separation between extraneous files and examples: all the extra files are in directories, and only the examples are plain files (besides a `.travis.yml` and `README.md`).

**Comment by mrocklin** [comment]
I've hidden all of the extraneous directories in https://github.com/dask/dask-examples/pull/17

I'm still inclined to group notebooks into directories

**Comment by guillaumeeb** [comment]
Is there still things to do here? Should we close it once #41 is merged?

Should we close #13 without merging it?
