### ISSUE TITLE
Add example for embarrassingly parallel parametrized computation

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-examples#30]
Would this be of interest for people here to have an example with Dask showing how to do embarrassingly parallel computation on some simulation code?

The idea is that you have a code that does some heavy computation, it takes some parameters and return one or more values as a result. You want to evaluate the program on a grid, with a predefined list of inputs, or maybe with some randomly picked input (Montecarlo simulation). The code run in a few seconds or minutes with each input, and you've got to run it with several thousand or more different inputs. It is something that is often seen in HPC with some physical simulations, and this is not really efficient doing it only with job arrays or alike in PBS or some other schedulers.

Basic steps would be:
1. Generate or read a list of parameters
2. Use client.map or delayed to iterate over these parameters and run the computation
3. Gather all results, and save them on a tabular file.
4. Eventually do some analysis on the result, mean or other aggregations.

I'm currently working on something like that for showing it to our scientists.

Any thought on that?

**Comment by mrocklin** [comment]
I agree that this is a common workflow and a simple version of it would be
a nice example to include.
