### ISSUE TITLE
Static Site Feedback

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask-examples#43]
http://dask.org/dask-examples/

- Some of the code examples are a bit wide, causing a horizontal scrollbar
- The Client repr could be improved with some external CSS
![screen shot 2018-09-16 at 3 15 11 pm](https://user-images.githubusercontent.com/1312546/45600504-62abfd00-b9c3-11e8-90c4-f749df085531.png)
- dask.array output repr is a bit too wide 
![screen shot 2018-09-16 at 3 16 27 pm](https://user-images.githubusercontent.com/1312546/45600514-84a57f80-b9c3-11e8-8e83-15c464212b04.png)
- pandas HTML table is a bit ugly, some output too long (dataframe.html) 
![screen shot 2018-09-16 at 3 17 11 pm](https://user-images.githubusercontent.com/1312546/45600523-a3a41180-b9c3-11e8-9d50-4ea89bc5c95d.png)
- Section headers feel a bit squished into the previous content, too far from the section content 
![screen shot 2018-09-16 at 3 17 57 pm](https://user-images.githubusercontent.com/1312546/45600537-c20a0d00-b9c3-11e8-859c-bffe048a38f6.png)
- Our `code` bocks have the yellow background we've removed in a few places IIRC 
![screen shot 2018-09-16 at 3 19 29 pm](https://user-images.githubusercontent.com/1312546/45600547-f4b40580-b9c3-11e8-9ae7-4a2991a9c5d9.png)
- http://dask.org/dask-examples/dataframes/01-data-access.html isn't executing, I think because the video which needs to be check-in as executed. Need to set `nbsphinx_execute = 'always'` in our conf.
- http://dask.org/dask-examples/machine-learning/parallel-prediction.html update links to be absolute links to the API pages, not `:class:` refs
- Empty cell at the bottom of http://dask.org/dask-examples/machine-learning/xgboost.html
- Long output in http://dask.org/dask-examples/embarrassingly-parallel.html#Using-the-Futures-API
- Empty cell at the bottom of http://dask.org/dask-examples/embarrassingly-parallel.html#Doing-some-analysis-on-the-results
- Section headers off in http://dask.org/dask-examples/embarrassingly-parallel.html. The top one should be an `#` and the rest `##`.

**Comment by mrocklin** [comment]
This is a nice list.  Thanks for putting it together. 

In https://github.com/dask/dask-sphinx-theme/pull/8 I've resolved the green background for `pre` cells.  I suspect that by removing the `In/Out` prefixes that we'll improve the horizontal space in a couple cases.  

I suspect that you have some thoughts on how to improve dataframe styling :)
