### ISSUE TITLE
Docs aren't updating

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#58]
I think that our docs don't seem to be updating after we push.  We've added a couple notebooks in recent months that aren't showing up.

cc @TomAugspurger and @jcrist who might know a bit more about the doc build system here (I think doctr)

**Comment by jcrist** [comment]
The docs are being built, and pushed, but the new notebooks (e.g. glm) have no link in the index. Here's the GLM one: http://examples.dask.org/machine-learning/glm

**Comment by mrocklin** [comment]
Interesting.  I've added those to the index here: https://github.com/dask/dask-examples/pull/59

Any idea why the Applications section isn't coming up in the index?

**Comment by jcrist** [comment]
Those are failing to build, and then the toctree has no items, warns, and then is ignored: https://travis-ci.org/dask/dask-examples/builds/487074754#L1596

**Comment by jcrist** [comment]
Oop, nvm, they are building. The links should be `applications/*` though, that's the issue.

**Comment by mrocklin** [comment]
Gah.  Thank you.  My brain is overly distracted these days.
