### ISSUE TITLE
Lab extension plots not showing up

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#64]
Plots are no longer showing up.  I believe that this may be due to recent security changes in JLab. Any suggestions on how to handle this @ian-r-rose ?

I've also pushed a binder with more up-to-date versions here: https://mybinder.org/v2/gh/mrocklin/dask-examples/update-labextension?urlpath=lab

**Comment by mrocklin** [comment]
```
[bokeh] setting log level to: 'info'
connection.js:55 WebSocket connection to 'wss://hub.mybinder.org/user/mrocklin-dask-examples-pc2yzpdk/proxy/8787/workers/ws?bokeh-protocol-version=1.0&bokeh-session-id=g8vm0oUbBxywswUzxeq0KHgF4lrQHKD3ezTwSkp8Pet7' failed: Error during WebSocket handshake: Unexpected response code: 502
t.connect @ connection.js:55
connection.js:287 [bokeh] Failed to connect to Bokeh server Error: Could not open websocket
(anonymous) @ connection.js:287
connection.js:208 [bokeh] Lost websocket 0 connection, 1006 ()
connection.js:95 [bokeh] Websocket connection 0 disconnected, will not attempt to reconnect
```

**Comment by ian-r-rose** [comment]
I'm not sure what the problem is just yet: I don't think it's changes to recent iframe-ing security policies in JupyterLab, since those are in the prerelease, rather than `0.35`. Have there been any recent changes to `distributed` or the bokeh webserver that might result in a different security model?

**Comment by ian-r-rose** [comment]
I see the same issue in `dask/dask-examples` master, which suggests to me that there may be some dependency that released a breaking change.

**Comment by ian-r-rose** [comment]
Could also be related to a recent snafu with Tornado 6, which was released a couple of weeks ago.

**Comment by ian-r-rose** [comment]
Possible other related issues: jupyterhub/jupyter-server-proxy#109, jupyterhub/jupyter-server-proxy#115

**Comment by ian-r-rose** [comment]
@mrocklin did dask have any troubles with tornado 6?

**Comment by mrocklin** [comment]
A couple small ones, but we cleaned them up a release ago
