### ISSUE TITLE
Add Prefect example?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#72]
@cicdw any interest in adding an example notebook building a Prefect workflow to examples.dask.org ?  https://github.com/dask/dask-examples#contributing

This site gets decent traffic, and we provide testing, HTML static output generation, and serving as a binder.

**Comment by cicdw** [comment]
Yea, absolutely!  It might take me a bit to come up with a good example, but I'm definitely on board.

**Comment by cicdw** [comment]
Would you consider the [Google BigQuery datasets](https://cloud.google.com/bigquery/public-data/) suitable for an external data source?

**Comment by mrocklin** [comment]
Sure, that sounds great assuming we can access then anonymously.

**Comment by cicdw** [comment]
Just for tracking, small update: I can't query the BigQuery datasets anonymously, so I've come up with a toy example with sqlite3 that will use a reasonably large number of tasks, and highlights how Prefect / Dask work together.  My personal goal is to have up for review late next week.

**Comment by mrocklin** [comment]
Woot.  Thanks for keeping on this Chris.

**Comment by martindurant** [comment]
ping @cicdw , looking forward to seeing your example

**Comment by cicdw** [comment]
Sorry for the delay! We just started our platform rollout and time got away from me.  Will tackle this ASAP.

**Comment by martindurant** [comment]
Glad to hear it :)

**Comment by cicdw** [comment]
I've gotten most of the way through with this, so should have it up for review in the next day or two!
