### ISSUE TITLE
Add example showing resilience against worker deaths?

### ISSUE THREAD

**Issue by willirath** [dask/dask-examples#74]
In preparation for a dask-jobqueue workshop, I'm playing with partially preemptible clusters.  Would it make sense to add an example using a mocked up partially resilient `LocalCluster` to show that dask is able to handle dying ressources?

A draft that works on the current examples binder is here:
https://gist.github.com/willirath/c6e5e26204b33bb4415923329a6b8723

**Comment by TomAugspurger** [comment]
I think that would make for a nice example. Based on the example, my main
comment would be adding a link to
https://distributed.dask.org/en/latest/resilience.html, and noting that a
node getting preempted
is essentially a hardware failure:
https://distributed.dask.org/en/latest/resilience.html#hardware-failures.

**Comment by TomAugspurger** [comment]
I think this was closed by https://github.com/dask/dask-examples/pull/75
